version: '3'

services:
  web:
    build: ./docker/web
    container_name: web
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "80:80"
    volumes:
      - ./batch:/docker_php_batch/batch
      - ./app:/docker_php_batch/app
    depends_on:
      - db

  db:
    build: ./docker/db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - "docker_php_batch_data:/var/lib/mysql"
      - "./docker/db/init:/docker-entrypoint-initdb.d"
      - "./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=pass
    ports:
      - 8080:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    depends_on:
      - db

volumes:
  docker_php_batch_data:
    driver: local
